### ISSUE TITLE
Support a requested_action workflow on PRs

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#1063]
See [Check runs and requested actions](https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-checks?apiVersion=2022-11-28#check-runs-and-requested-actions) and [the API reference](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#get-a-check-run:~:text=Properties%20of%20output-,actions%20array%20of%20objects,-Possible%20further%20actions)

If we're able to get the webhook URL for the check run, then we can support this feature, so things like adding labels or altering descriptions can be done by the check itself and not just by users.

**Comment by pkaminski** [comment]
This doesn't seem feasible to me for a few reasons:
1. It doesn't look like GitHub surfaces the `actions` array in the check run data structure, either via REST or GraphQL, even though you pass it in when creating the check run.  This means we can't get a list of the actions.
2. There's no API to programmatically trigger an action.
3. There's no way that I know of to get the webhook URL for an another app -- I believe those are intended to be secret.
4. Webhooks can be (and usually are) set up with a secret used to sign them so invalid ones from rogue apps (like we would be!) can be rejected.  There's definitely no way to get our hands on that secret.

It's pretty hard to search for discussions and workarounds related to this, though, since "GitHub Actions" is a different thing from "GitHub check run actions" and tends to get discussed a lot more.  FWIW I haven't found any questions regarding how to trigger check run actions from a third party app, much less solutions.

**Comment by fahhem** [comment]
Seeing that we can't support GitHub check's API, and after some internal discussion, there may be a way to support the same need but without github's intercession:

A completion condition could, in a new field, report requested_actions with a schema more tailored to our needs. An extension to the existing API: https://docs.reviewable.io/repositories.html?highlight=completion#custom-review-completion-condition

```yaml
userActions:
- label: "Submit commit for ChatGPT review"
  description: "..."
  # either userURL or webhook
  userURL: "https://chatgpt.internal/submit/{PRnum}"
  webhook:
    url: "https://chatgpt.internal/submitByReviewable/{PRnum}"
    headers:
    - Content-Type: application/json
    payload: '{"key": "value"}'
```
(This is in YAML for readability, but it would be in JSON in the actual output)

If `userURL` is specified, then clicking on the action will open a new tab with that URL. If `webhook` is specified, then the user clicking on the action will instead show a success icon/short animation and the backend will send the payload to the webhook.
