### ISSUE TITLE
Skipped check considered as error

### ISSUE THREAD

**Issue by pcorpet** [Reviewable/Reviewable#1152]
As of last week, it seems that Reviewable has started considering "skipped" checks in GitHub as errors.

Here's how it renders on GitHub
<img width="888" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/2870f2c0-4228-4c87-819c-ed2ca9ce41ec">

Here's the check bubble on the PR page on Reviewable
<img width="462" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/f5af359f-196d-4e5e-a639-345bc927ec75">

And here's the PR list view in Reviewable
<img width="242" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/3443b8be-ecd4-4442-8238-faf2992b42f7">

Did I change the config? is there a way to fix it somehow?

Note, this is an example of a GitHub action config. The "if" line is the one making it skip in other cases.
```
name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
       ...
```
