### ISSUE TITLE
Confusing diff visualization

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#326]
This diff representation is too aggressive in trying to find similar text. It was really confusing, even to the PR author.

![image](https://cloud.githubusercontent.com/assets/187063/15747993/1663e044-28ab-11e6-9c34-744189b5aaa1.png)

![image](https://cloud.githubusercontent.com/assets/187063/15748032/4a8a8436-28ab-11e6-975f-42ca7eac95b3.png)

On GitHub:

![image](https://cloud.githubusercontent.com/assets/187063/15748067/68368fa2-28ab-11e6-8622-06bcb9f5a7d1.png)

![image](https://cloud.githubusercontent.com/assets/187063/15748101/84718744-28ab-11e6-84af-4cd2891dc2ad.png)

`git diff`:

![image](https://cloud.githubusercontent.com/assets/187063/15748207/e6325d50-28ab-11e6-8650-723e4a3086ef.png)

This can be reproduced with the following two code snippets.

```
    outspan = pyinter.openclosed(MIN_DATE, datetime(2014, 1, 1, tzinfo=UTC))
    span = fixed_window_length_input_loader._compute_desired_span(outspan, inputs)
```

```
    (span, _) = fixed_window_length_input_loader._compute_span_to_load(env)
```

**Comment by pkaminski** [comment]
Another one reported by @mxxcon, diff these two files:
```
websites:
    - name: ADP
      url: https://www.adp.com
      twitter: adp
      img: adp.png
      tfa: No

    - name: Adirondack Insurance Exchange
      url: http://www.aie-ny.com/
      img: adirondackinsurnaceexchange.png
      tfa: No

    - name: Credit Karma
      url: https://www.creditkarma.com
      twitter: creditkarma
```
```
websites:
    - name: Adirondack Insurance Exchange
      url: http://www.aie-ny.com/
      img: adirondackinsurnaceexchange.png
      tfa: No

    - name: ADP
      url: https://www.adp.com
      twitter: adp
      img: adp.png
      tfa: No

    - name: Credit Karma
      url: https://www.creditkarma.com
      twitter: creditkarma
```
The diff picks up the wrong `tfa: No` -- it should pay attention to the blank line separating the sections.  Or even better, detect that it's a block move in the first place.
